# tickers.py (clean, company-essentials only)

tickers = {
    # General Companies
    "ABBV": ["AbbVie"],
    "ABNB": ["Airbnb"],
    "ACI":  ["Albertsons"],
    "AEM":  ["Agnico Eagle Mines"],
    "AGI":  ["Alamos Gold"],
    "AIG":  ["American International Group"],
    "ALB":  ["Albemarle"],
    "ALRM": ["Alarm.com"],
    "AMZN": ["Amazon"],
    "APLE": ["Apple Hospitality REIT"],
    "BDX":  ["Becton Dickinson"],
    "BG":   ["Bunge"],
    "BMY":  ["Bristol Myers Squibb"],
    "BWA":  ["BorgWarner"],
    "CHGG": ["Chegg"],
    "CLVT": ["Clarivate"],
    "CRM":  ["Salesforce"],
    "CRWD": ["CrowdStrike"],
    "CTO":  ["CTO Realty Growth"],
    "CNH":  ["CNH Industrial"],
    "CVX":  ["Chevron"],
    "DOCU": ["DocuSign"],
    "DUK":  ["Duke Energy"],
    "EEFT": ["Euronet Worldwide"],
    "ENR":  ["Energizer"],
    "EPAM": ["EPAM Systems"],
    "EPR":  ["EPR Properties"],
    "ET":   ["Energy Transfer"],
    "ETSY": ["Etsy"],
    "EXPE": ["Expedia"],
    "F":    ["Ford"],
    "FTI":  ["TechnipFMC"],
    "FWONK":["Formula One Group"],
    "GBX":  ["Greenbrier"],
    "GMRE": ["Global Medical REIT"],
    "GOLD": ["Barrick Gold"],
    "GTLS": ["Chart Industries"],
    "HCI":  ["HCI Group"],
    "IAUX": ["iShares Gold Trust"],
    "IBM":  ["IBM"],
    "IFF":  ["International Flavors & Fragrances"],
    "INVA": ["Innoviva"],
    "J":    ["Jacobs Engineering"],
    "JAZZ": ["Jazz Pharmaceuticals"],
    "JCI":  ["Johnson Controls"],
    "JHX":  ["James Hardie"],
    "JNJ":  ["Johnson & Johnson"],
    "KHC":  ["Kraft Heinz"],
    "KIM":  ["Kimco Realty"],
    "KR":   ["Kroger"],
    "LAC":  ["Lithium Americas"],
    "LBRDA":["Liberty Broadband"],
    "LCII": ["LCI Industries"],
    "LEG":  ["Leggett & Platt"],
    "LITE": ["Lumentum"],
    "LNT":  ["Alliant Energy"],
    "LSXMA":["Liberty SiriusXM Group"],
    "LXP":  ["LXP Industrial Trust"],
    "LYFT": ["Lyft"],
    "MCD":  ["McDonald's"],
    "MET":  ["MetLife"],
    "MGM":  ["MGM Resorts"],
    "MMM":  ["3M"],
    "MRK":  ["Merck"],
    "NRG":  ["NRG Energy"],
    "NWL":  ["Newell Brands"],
    "FLG":  ["Fulgent Genetics"],
    "OBNNF":["Osisko Gold Royalties"],
    "PEB":  ["Pebblebrook Hotel Trust"],
    "PFE":  ["Pfizer"],
    "PINE": ["Alpine Income Property Trust"],
    "PPL":  ["PPL Corporation"],
    "RBLX": ["Roblox"],
    "SFL":  ["Ship Finance International"],
    "SHEL": ["Shell"],
    "SIRI": ["Sirius XM"],
    "SKE":  ["Skeena Resources"],
    "SNOW": ["Snowflake"],
    "STWD": ["Starwood Property Trust"],
    "T":    ["AT&T"],
    "TSM":  ["Taiwan Semiconductor Manufacturing", "TSMC"],
    "TSN":  ["Tyson Foods"],
    "VICI": ["VICI Properties"],
    "VTRS": ["Viatris"],
    "VZ":   ["Verizon"],
    "WBD":  ["Warner Bros Discovery"],
    "WY":   ["Weyerhaeuser"],
    "XOM":  ["ExxonMobil"],
    "VSH":  ["Vishay Intertechnology"],

    # Credit-Only Companies
    "SCI":  ["Service Corporation International"],
    "C":    ["Citigroup"],
    "GS":   ["Goldman Sachs"],
    "JPM":  ["JPMorgan Chase"],
    "WFC":  ["Wells Fargo"],
    "GLPI": ["Gaming and Leisure Properties"],
    "HPQ":  ["HP Inc."],

    # Banks
    "ABCB": ["Ameris Bancorp"],
    "ALRS": ["Alerus Financial"],
    "BANC": ["Banc of California"],
    "BANCPU":["Banc of California Preferred Unit"],
    "BBVA": ["Banco Bilbao Vizcaya Argentaria"],
    "BNPQY":["BNP Paribas"],
    "HWC":  ["Hancock Whitney"],
    "ING":  ["ING Group"],
    "JPMPU":["JPMorgan Preferred Unit"],
    "SCGLY":["Societe Generale"],
    "SSB":  ["South State"],
    "SBCF": ["Seacoast Banking"],
    "MTB":  ["M&T Bank"],
    "FHN":  ["First Horizon"],
    "BMBN": ["Benchmark Bankshares"],
    "BORT": ["Bank of the Ozarks"],
    "BRBS": ["Blue Ridge Bankshares"],
    "BRKL": ["Brookline Bancorp"],
    "CPKF": ["Chesapeake Financial"],
    "CSBB": ["CSB Bancorp"],
    "CWBC": ["Community West Bancshares"],
    "MCHN": ["Mechanics Bank"],
    "EBMT": ["Eagle Bancorp Montana"],
    "EXSR": ["Exchange Bank"],
    "FBIZ": ["First Business Financial"],
    "FCCO": ["First Community"],
    "FISI": ["Financial Institutions"],
    "FLIC": ["First of Long Island"],
    "FMBM": ["First National Bank"],
    "FNCB": ["FNCB Bancorp"],
    "FRAF": ["Franklin Financial"],
    "FSBH": ["First South Bancorp"],
    "FXNC": ["First National Corporation"],
    "4100810": ["First Financial Australia"],
    "LFGP": ["Legacy First Group"],
    "MFGI": ["M&F Bancorp"],
    "MNSB": ["MainStreet Bancshares"],
    "PFIS": ["Peoples Financial Services"],
    "PKBK": ["Parke Bancorp"],
    "PTBS": ["Potomac Bancshares"],
    "SBFG": ["SB Financial Group"],
    "SOBS": ["SouthBank"],
    "TSBK": ["Timberland Bancorp"],
    "QABA": ["Community Bank Index"],
}
