# tickers.py (auto-cleaned from Excel)

tickers = {
    "ABBV": ['AbbVie'],
    "ABCB": ['Ameris Bancorp'],
    "ACI": ['Albertsons'],
    "AEM": ['Agnico Eagle Mines'],
    "AGI": ['Alamos Gold'],
    "AIG": ['American International Group'],
    "ALB": ['Albemarle'],
    "ALRS": ['Alerus Financial'],
    "APLE": ['Apple Hospitality REIT'],
    "BANC": ['Banc of California'],
    "BDX": ['Becton Dickinson'],
    "BG": ['Bunge'],
    "BMBN": ['Benchmark Bankshares'],
    "BMY": ['Bristol Myers Squibb'],
    "BORT": ['Bank of the Ozarks'],
    "BRBS": ['Blue Ridge Bankshares'],
    "BRKL": ['Brookline Bancorp'],
    "BWA": ['BorgWarner'],
    "CLVT": ['Clarivate'],
    "CNH": ['CNH Industrial'],
    "CPKF": ['Chesapeake Financial'],
    "CSBB": ['CSB Bancorp'],
    "CTO": ['CTO Realty Growth'],
    "CVX": ['Chevron'],
    "CWBC": ['Community West Bancshares'],
    "DUK": ['Duke Energy'],
    "EEFT": ['Euronet Worldwide'],
    "ENR": ['Energizer'],
    "EPR": ['EPR Properties'],
    "ET": ['Energy Transfer'],
    "ETSY": ['Etsy'],
    "EXSR": ['Exchange Bank'],
    "F": ['Ford'],
    "FBIZ": ['First Business Financial'],
    "FCCO": ['First Community'],
    "FISI": ['Financial Institutions'],
    "FLG": ['Fulgent Genetics'],
    "FLIC": ['First of Long Island'],
    "FMBM": ['First National Bank'],
    "FRAF": ['Franklin Financial'],
    "FSBH": ['First South Bancorp'],
    "FWONK": ['Formula One Group'],
    "FXNC": ['First National Corporation'],
    "GBX": ['Greenbrier'],
    "GLPI": ['Gaming and Leisure Properties'],
    "GMRE": ['Global Medical REIT'],
    "GOLD": ['Barrick Gold'],
    "HCI": ['HCI Group'],
    "HWC": ['Hancock Whitney'],
    "IAUX": ['iShares Gold Trust'],
    "IFF": ['International Flavors & Fragrances'],
    "INVA": ['Innoviva'],
    "J": ['Jacobs Engineering'],
    "JAZZ": ['Jazz Pharmaceuticals'],
    "JCI": ['Johnson Controls'],
    "JHX": ['James Hardie'],
    "JNJ": ['Johnson & Johnson'],
    "KHC": ['Kraft Heinz'],
    "KIM": ['Kimco Realty'],
    "KR": ['Kroger'],
    "LAC": ['Lithium Americas'],
    "LBRDA": ['Liberty Broadband'],
    "LCII": ['LCI Industries'],
    "LEG": ['Leggett & Platt'],
    "LFGP": ['Legacy First Group'],
    "LNT": ['Alliant Energy'],
    "LSXMA": ['Liberty SiriusXM Group'],
    "LXP": ['LXP Industrial Trust'],
    "LYFT": ['Lyft'],
    "MET": ['MetLife'],
    "MFGI": ['M&F Bancorp'],
    "MNSB": ['MainStreet Bancshares'],
    "MRK": ['Merck'],
    "MTB": ['M&T Bank'],
    "NRG": ['NRG Energy'],
    "NWL": ['Newell Brands'],
    "OBNNF": ['Osisko Gold Royalties'],
    "PEB": ['Pebblebrook Hotel Trust'],
    "PFE": ['Pfizer'],
    "PFIS": ['Peoples Financial Services'],
    "PINE": ['Alpine Income Property Trust'],
    "PKBK": ['Parke Bancorp'],
    "PPL": ['PPL Corporation'],
    "PTBS": ['Potomac Bancshares'],
    "SBCF": ['Seacoast Banking'],
    "SBFG": ['SB Financial Group'],
    "SCI": ['Service Corporation International'],
    "SFL": ['Ship Finance International'],
    "SHEL": ['Shell'],
    "SIRI": ['Sirius XM'],
    "SKE": ['Skeena Resources'],
    "SOBS": ['SouthBank'],
    "SSB": ['South State'],
    "STWD": ['Starwood Property Trust'],
    "T": ['AT&T'],
    "TSBK": ['Timberland Bancorp'],
    "TSN": ['Tyson Foods'],
    "VICI": ['VICI Properties'],
    "VSH": ['Vishay Intertechnology'],
    "VTRS": ['Viatris'],
    "VZ": ['Verizon'],
    "WY": ['Weyerhaeuser'],
    "XOM": ['ExxonMobil'],
    "FOUR": ['Shift4 Payments'],
}
